### ISSUE TITLE
IotaAPI.getTransfers() always throws ArgumentException for specific (seed, index) combinations

### ISSUE THREAD

**Issue by mikrohash** [iotaledger/iota.lib.java#90]
When calling this method:

    api.getTransfers(seed, 2, index, index+1, false);

I frequently receive this exception:

    jota.error.ArgumentException: [{"error":"Could not complete request","duration":43}]
        at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
        at jota.IotaAPICore.getTrytes(IotaAPICore.java:292)
        at jota.IotaAPI.findTransactionsObjectsByHashes(IotaAPI.java:268)
        at jota.IotaAPI.findTransactionObjectsByAddresses(IotaAPI.java:297)
        at jota.IotaAPI.bundlesFromAddresses(IotaAPI.java:132)
        at jota.IotaAPI.getTransfers(IotaAPI.java:116)

Furthermore, this exception only happens for very specific `(seed, index)` combinations. So it works for the paramers `(seed = 'PDIZO...', index = 29)`, but not for `(seed = 'PDIZO...', index = 30)`. I can call the latter one a hundred times, yet the exception will continue to be thrown every single time. I have tried connecting to different nodes, but this did not help either.

For obvious reason, I will not post any explicit seed in here. If, however, any developer of this repository wants to replicate the error, I will happily provide you with an example seed with a rather low balance.

**Comment by ezienecker** [comment]
@mikrohash is this issue still relevant? Can you provide a sample? meanwhile the code base is a bit different.
