### ISSUE TITLE
library is automatically catching and printStackTracing ArgumentException when receiving 400 error from getTransactionsToApprove()

### ISSUE THREAD

**Issue by mikrohash** [iotaledger/iota.lib.java#91]
https://github.com/iotaledger/iota.lib.java/blob/39c6442d941e03ea9cb0e0598f32129dec28057e/jota/src/main/java/jota/IotaAPICore.java#L72

Maybe this is intentional, but I don't get how this is useful. This exception is thrown when calling IotaAPICore.getTransactionsToApprove(), but receiving a 400 error from the IRI (very common: `[{"error":"inconsistent tips pair selected","duration":4630}]`).

But since the exception is catched, the program will just continue to be executed and return the call reponse - in contrast to a 401 or 500 error where an IllegalAccessError is thrown correctly. That means that anyone calling IotaAPICore.getTransactionsToApprove(), will not be informed about a 400 error during the request.

**Comment by mikrohash** [comment]
More examples of when this exception is thrown:

    jota.error.ArgumentException: [{"error":"Index: 1, Size: 1","duration":6451}]
        at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
        at jota.IotaAPICore.getTransactionsToApprove(IotaAPICore.java:303)

    jota.error.ArgumentException: [{"error":"inconsistent tips pair selected","duration":270}]
        at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
        at jota.IotaAPICore.getTransactionsToApprove(IotaAPICore.java:303)
        
    jota.error.ArgumentException: [{"duration":4365}]
        at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
        at jota.IotaAPICore.getTransactionsToApprove(IotaAPICore.java:303)
